eureka:
  instance:
    hostname: user-service
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql-service:3306/smc_user
    username: root
    password: just4mysql
  mail:
    host: smtp.163.com
    port: 587
    username: guydsh@163.com
    password: vslyrzjbmaiuaipf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true